### ISSUE TITLE
Application freezes after being minimized

### ISSUE THREAD

**Issue by anguzo** [SuRGeoNix/Flyleaf#218]
While trying to integrate Flyleaf into my WPF application I encountered a problem which was not present in the samples (actually in the FlyleafPlayer (WPF Control) sample the application crashes when minimizing, but it's not related to my problem). Application freezes after minimizing. I went through the source code and didn't find any idea on why the freezing happens. I also checked several options for defining config, initializing the control etc. The fact is when I add WPF control the application freezes on minimizing even if player is not playing anything. I also made several test applications and the don't share the same behavior.
I also tried isolating Player instance in separate ViewModel and play without the control and there is no problem.
For reference I use .NET Framework 4.8 and just updated Flyleaf to v3.6.3.

**Comment by SuRGeoNix** [comment]
```
actually in the FlyleafPlayer (WPF Control) sample the application crashes when minimizing
```
That sounds already bad. That's the sample from the releases, so the release application crashes as well when minimized? Can you check the event viewer for an error message?

Did you notice if your issues happens when you use more than one FlyleafHost controls? If so, you should look into Utils/ZOrderHandler.cs

Otherwise it's something in Controls/WPF/FyleafHost.cs but it more sounds like a different issue for me, possible with .NET Framework.

Can you help me reproduce it so I can resolve this easier?

**Comment by anguzo** [comment]
The problem with WPF Control sample can be reproduced by following steps:
1. Run the player app
2. Open some video from file(I opened mp4)
3. Maximize
4. Minimize
In my case it throws following exception:
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
in Renderer.cs at line 914.
![image](https://user-images.githubusercontent.com/46993018/204995429-952119b4-2edd-40bd-999c-aca323b8420e.png)
I confirm that release app also crashes it this case.
![image](https://user-images.githubusercontent.com/46993018/204996350-2c29a742-da76-4059-8c2b-1b505e6c8ef1.png)
![image](https://user-images.githubusercontent.com/46993018/204996375-f09abc15-27a6-4e8c-9381-8c5e0549c955.png)

I don't believe this behavior is what causes my app to freeze, but hope it helps.

In my app I use one FlyleafHost control and I did some testing with Flyleaf on .NET Framework and couldn't reproduce the freeze in even harder situations(like making ItemsControl UniformGrid which automatically populates the view based on ObservableCollection of VMs that encapsulate the Players). 12 players playing and no issues. Beautiful performance by the way, HighPerformanceTimers set to false decreases Memory usage from 2.3 to 1.9, don't know if there are other benefits. Actually as a side note the Wiki statement "Use this for multiple players" was confusing to me since I am not familiar with this whole Windows internal timer theme. I thought what should I use - the statement of HighPerformanceTimers set to false or use HighPerformanceTimers hence set it to true.

And also I tested WinFormsHost hosting WF Control in my WPF application that freezes and there is no issue using it.

**Comment by SuRGeoNix** [comment]
I don't understand why you see that this is not related to your issue. Both issues that you say (I can't reproduce them by the way) freezing the application after minimize (right?). And from your logs (Flyleaf.FirstRun.log would help too) seems something is wrong with the renderer. I will need more info for you system (OS/GPU/DirectX version etc.). But again that doesn't make sense as it works in some cases? You can enable native debugging and see the exact error from Vortice/DirectX. As I can't reproduce it I can assist you with anydesk/skype, just drop me an email.

It might worth testing if the same error happens with Flyleaf Video Processor (by forcing it) on Player's Config

```
config.Video.VideoProcessor = VideoProcessors.Flyleaf;
```

Now for the HighPerformanceTimers, Windows' timers have a setting for how much accurate to be. For example when your application says Sleep(10ms) if the Windows' timer is set to 15ms accuracy then it might sleep 1ms or 15ms you can't know for sure. Flyleaf sets this timer to 1ms to ensure smooth playback (but only when it plays to save power from the system as it requires more power/battery for that). But in case of multiple players it might loose that 1ms (windows have a lot of issues with this setting) and on some point you might notice frame drops so it is advised to set HighPerformanceTimers to true on multiplayers.

**Comment by SuRGeoNix** [comment]
Turn the FreeSync Off from your AMD Adrenalin -> Settings -> Display

**Comment by SuRGeoNix** [comment]
Do you have HDR display, can you try turn HDR off and see if you still have issues also with the iGPU?

**Comment by anguzo** [comment]
I disabled this option in AMD Software for one of my displays, second one doesn't support Freesync.
![image](https://user-images.githubusercontent.com/46993018/205069401-89b86427-1f17-419e-9c80-2438231aff29.png)
But the issue still persists.
Neither of my displays is HDR and I also tried disconnecting one of the displays.

**Comment by SuRGeoNix** [comment]
Can you do a quick skype to clarify the issue? https://join.skype.com/invite/MMq73y3YXARk

**Comment by SuRGeoNix** [comment]
Thanks, just to sum-up again, it seems you have indeed two different issues

1) D3D11 Video Processor (related with the your GPU as it does not happen in other systems)

The only difference that I saw with my RX 580 was in Video Processor Feature Caps your GPU does not support LumaKey (not sure yet if that has anything to do with that issue). I cannot understand how the D3D11 works fine for you with WinForms but not in WPF.

2) The FlyleafHost.Wpf freezes the app during minimize

I will need to reproduce it but I just notice another possible reason for that :-

```
[Output #1] \\.\DISPLAY1         [Id: 0   	, Top: 0   , Left: 0   , Width: 3840, Height: 2160, Ratio: [16:9]
[Output #2] \\.\DISPLAY2         [Id: 1   	, Top: 854 , Left: -2880, Width: 2880, Height: 1620, Ratio: [16:9]
```

You have two displays and the 2nd one has a negative Left which might be the reason for the crash (you might want to disconnect it and retry)

**Comment by anguzo** [comment]
To make things clear about my app:
1. Freezes happened on RX 5500 XT, 1050Ti, and iGPUs with WPF control. 
2. With WinForms there is no such problem. 
3. Changing the VideoProcessor to Flyleaf also didn't help. 
4. WPF control in my application even without Player attached to it and without any parameters altered freezes app on minimize if added. If I remove it from XAML then there is no such behavior.
5. As you suggested there must be some component in my application (in code behind or in XAML) that conflicts with Flyleaf somehow. I will research this.
6. In my opinion there must be some issue on minimizing - some event, logic that is being executed when the host window OnStateChanged event is fired. 
7. Also Surface is a Window, so a Window hosted in Window might be the problem. For example, as I mentioned with the auto-populated UniformGrid(ObservableCollection of VMs on which contents depends amount of player controls and their layout), if you don't invoke Surface.Close when add and remove the VM and the WPF control is created, when it's "destroyed" the Surface is not, so it brings to a situation like this:
![image](https://user-images.githubusercontent.com/46993018/205089016-c9d88119-1e3e-48a2-b258-19b1d5229607.png)

About the release WPF Flyleaf app:
1. Setting VideoProcessor to Flyleaf solves issue with my AMD GPU.
2. Going to Windows Graphics settings -> Graphics performance reference -> Browse Flyleaf app -> Set to Power Saving/iGPU
Flyleaf plays video with distorted colors(graphical issue on UHD 630 and 770 I mentioned).
3. I tested with one display attached and the issue persists.
4. When I attached second display back I also found out some kind of issue where Flyleaf crashes on startup when started not on primary display(probably related to by primary display being 4K on secondary FullHD). To reproduce this I opened Flyleaf folder in Explorer and when Explorer is on my primary display it starts but when Explorer is on secondary display it crashes.
![image](https://user-images.githubusercontent.com/46993018/205086414-2c150dad-70ab-4b0d-b880-3f098e065118.png)

**Comment by SuRGeoNix** [comment]
For the secondary screen crash probably this line is responsible:

```
var screen = Engine.Video.GetScreenFromPosition((int)host.Surface.Top, (int)host.Surface.Left);
```
which means that it cannot find in which screen it belongs. I tried a lot of different two screen different configuration without success reproducing it. You will need to debug it to see what's going on there :) It's also strange that your secondary's screen top is not 0, couldn't reproduce this either.

For the Surface Window, generally you don't really have options with WPF to create a custom renderer surface, you need a different handle. So yes it will create a new window and if you don't use it the application will not close properly (it will stay open without showing anything). But I don't create a new window each time you unload / load the control so I can't understand how did you manage to create so many windows from one control. Maybe you should separate the Views (FlyleafHosts) from Players so you can create a Pool of Players but not for FlyleafHosts.

Thanks again for your detailed feedback!

**Comment by SuRGeoNix** [comment]
Might worth re-testing with v3.6.4 as I've fixed a nasty bug with WndProc subclass (hook) in the renderer which could affect other hooks (e.g. might AMD hooks on it) and it would create a stack overflow.

**Comment by anguzo** [comment]
Nice, it's working now. I tried version 3.6.5 and it's working, it might also me related to some issues with Topmost attribute Window, but I am not sure. I also had an issue in 3.6.4 with removing and adding winforms host to user control children, but it is fixed in 3.6.5 as well. Thank you!

**Comment by SuRGeoNix** [comment]
That's good news cause I couldn't reproduce it. I guess the other minor issues still remain and I should review them in the future.
